version: '3.6'

services:

  postgis:
    image: pgrouting/pgrouting:13-3.1-3.1.3
    container_name: postgis_local
    env_file: .env
    volumes:
      - pgis-data:/var/lib/postgresql/data
      - ./sql-scripts/init-db.sql:/docker-entrypoint-initdb.d/1-init-db.sql
      - ./sql-scripts/insert-rows.sql:/docker-entrypoint-initdb.d/2-insert-rows.sql
      - ./sql-scripts/create-topology.sql:/docker-entrypoint-initdb.d/3-create-topology.sql
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '5433:5432'

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: pgadmin4_local
    env_file: .env
    restart: always
    depends_on:
      - postgis
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  

volumes:
  pgis-data:
  pgadmin-data: